// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: proto/peerlink/v1/peerlink.proto

package peerlinkv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PeerLink_EventStream_FullMethodName = "/peerlink.v1.PeerLink/EventStream"
)

// PeerLinkClient is the client API for PeerLink service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Top-level streaming service.
// Each peer establishes a single long-lived bidirectional stream.
type PeerLinkClient interface {
	EventStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PeerMessage, PeerMessage], error)
}

type peerLinkClient struct {
	cc grpc.ClientConnInterface
}

func NewPeerLinkClient(cc grpc.ClientConnInterface) PeerLinkClient {
	return &peerLinkClient{cc}
}

func (c *peerLinkClient) EventStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PeerMessage, PeerMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PeerLink_ServiceDesc.Streams[0], PeerLink_EventStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PeerMessage, PeerMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PeerLink_EventStreamClient = grpc.BidiStreamingClient[PeerMessage, PeerMessage]

// PeerLinkServer is the server API for PeerLink service.
// All implementations must embed UnimplementedPeerLinkServer
// for forward compatibility.
//
// Top-level streaming service.
// Each peer establishes a single long-lived bidirectional stream.
type PeerLinkServer interface {
	EventStream(grpc.BidiStreamingServer[PeerMessage, PeerMessage]) error
	mustEmbedUnimplementedPeerLinkServer()
}

// UnimplementedPeerLinkServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPeerLinkServer struct{}

func (UnimplementedPeerLinkServer) EventStream(grpc.BidiStreamingServer[PeerMessage, PeerMessage]) error {
	return status.Errorf(codes.Unimplemented, "method EventStream not implemented")
}
func (UnimplementedPeerLinkServer) mustEmbedUnimplementedPeerLinkServer() {}
func (UnimplementedPeerLinkServer) testEmbeddedByValue()                  {}

// UnsafePeerLinkServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PeerLinkServer will
// result in compilation errors.
type UnsafePeerLinkServer interface {
	mustEmbedUnimplementedPeerLinkServer()
}

func RegisterPeerLinkServer(s grpc.ServiceRegistrar, srv PeerLinkServer) {
	// If the following call pancis, it indicates UnimplementedPeerLinkServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PeerLink_ServiceDesc, srv)
}

func _PeerLink_EventStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PeerLinkServer).EventStream(&grpc.GenericServerStream[PeerMessage, PeerMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PeerLink_EventStreamServer = grpc.BidiStreamingServer[PeerMessage, PeerMessage]

// PeerLink_ServiceDesc is the grpc.ServiceDesc for PeerLink service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PeerLink_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "peerlink.v1.PeerLink",
	HandlerType: (*PeerLinkServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "EventStream",
			Handler:       _PeerLink_EventStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/peerlink/v1/peerlink.proto",
}
